/**
 * Regenerates the Nifty 200 datasets in this folder from the official NSE list.
 *
 * Usage:
 *   node generate.mjs            # re-download from NSE, then write all outputs
 *   node generate.mjs --offline  # rebuild outputs from the local CSV snapshot
 */
import { writeFileSync, readFileSync } from 'node:fs';

const CSV_URL = 'https://nsearchives.nseindia.com/content/indices/ind_nifty200list.csv';
const CSV_FILE = 'ind_nifty200list.csv';
const offline = process.argv.includes('--offline');

/** Minimal RFC-4180 parser: handles quoted fields containing commas. */
function parseCsv(text) {
  const rows = [];
  let row = [], field = '', quoted = false;
  for (let i = 0; i < text.length; i++) {
    const c = text[i];
    if (quoted) {
      if (c === '"') {
        if (text[i + 1] === '"') { field += '"'; i++; } else { quoted = false; }
      } else field += c;
    } else if (c === '"') quoted = true;
    else if (c === ',') { row.push(field); field = ''; }
    else if (c === '\n') { row.push(field); rows.push(row); row = []; field = ''; }
    else if (c !== '\r') field += c;
  }
  if (field.length || row.length) { row.push(field); rows.push(row); }
  return rows.filter(r => r.some(v => v.trim() !== ''));
}

async function fetchCsv() {
  const res = await fetch(CSV_URL, {
    headers: {
      'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0 Safari/537.36',
      Accept: 'text/csv,*/*',
      Referer: 'https://www.nseindia.com/',
    },
  });
  if (!res.ok) throw new Error(`NSE responded ${res.status}`);
  const text = await res.text();
  if (!text.startsWith('Company Name')) throw new Error('Unexpected CSV header from NSE');
  writeFileSync(CSV_FILE, text);
  return text;
}

const csv = offline ? readFileSync(CSV_FILE, 'utf8') : await fetchCsv();
const [header, ...rows] = parseCsv(csv);
const col = Object.fromEntries(header.map((h, i) => [h.trim(), i]));

const constituents = rows
  .map(r => ({
    symbol: r[col['Symbol']].trim(),
    name: r[col['Company Name']].trim(),
    sector: r[col['Industry']].trim(),
    series: r[col['Series']].trim(),
    isin: r[col['ISIN Code']].trim(),
  }))
  .sort((a, b) => a.symbol.localeCompare(b.symbol));

if (constituents.length !== 200) throw new Error(`Expected 200 constituents, got ${constituents.length}`);
const symbols = constituents.map(c => c.symbol);
if (new Set(symbols).size !== 200) throw new Error('Duplicate symbols in NSE list');

const asOf = new Date().toISOString().slice(0, 10);

writeFileSync('nifty200.json', JSON.stringify({ index: 'NIFTY 200', source: CSV_URL, asOf, count: constituents.length, constituents }, null, 2) + '\n');
writeFileSync('symbols.json', JSON.stringify(symbols, null, 2) + '\n');

const ts = `// AUTO-GENERATED by generate.mjs — do not edit by hand.
// Source: ${CSV_URL}
// Snapshot taken: ${asOf}

export interface Nifty200Constituent {
  /** NSE trading symbol, e.g. "RELIANCE". */
  symbol: string;
  /** Registered company name as published by NSE. */
  name: string;
  /** NSE macro-economic sector / industry bucket. */
  sector: string;
  /** NSE series, "EQ" for all current constituents. */
  series: string;
  isin: string;
}

export const NIFTY_200_AS_OF = '${asOf}';

export const NIFTY_200: readonly Nifty200Constituent[] = ${JSON.stringify(constituents, null, 2)} as const;

/** All 200 NSE trading symbols, alphabetically sorted. */
export const NIFTY_200_SYMBOLS: readonly string[] = NIFTY_200.map((c) => c.symbol);

/** Symbol -> constituent lookup. */
export const NIFTY_200_BY_SYMBOL: Readonly<Record<string, Nifty200Constituent>> =
  Object.fromEntries(NIFTY_200.map((c) => [c.symbol, c]));

export const isNifty200Symbol = (symbol: string): boolean =>
  Object.prototype.hasOwnProperty.call(NIFTY_200_BY_SYMBOL, symbol.toUpperCase());

/** Constituents grouped by NSE sector. */
export const NIFTY_200_BY_SECTOR: Readonly<Record<string, Nifty200Constituent[]>> =
  NIFTY_200.reduce<Record<string, Nifty200Constituent[]>>((acc, c) => {
    (acc[c.sector] ||= []).push(c);
    return acc;
  }, {});

/** Yahoo Finance / yfinance style ticker, e.g. "RELIANCE" -> "RELIANCE.NS". */
export const toYahooTicker = (symbol: string): string => \`\${symbol.toUpperCase()}.NS\`;
`;
writeFileSync('nifty200.ts', ts);

console.log(`Wrote ${constituents.length} constituents (as of ${asOf}) to nifty200.json, symbols.json, nifty200.ts`);
